<?php

use Drupal\pp_taxonomy_manager\Entity\PPTaxonomyManagerConfig;
use Drupal\pp_taxonomy_manager\PPTaxonomyManager;

/**
 * Implements hook_taxonomy_term_delete().
 */
function pp_taxonomy_manager_taxonomy_term_delete(\Drupal\taxonomy\Entity\Term $term) {
  PPTaxonomyManager::deleteTaxonomyTerm($term);
}

/**
 * Implements hook_taxonomy_vocabulary_delete().
 */
function pp_taxonomy_manager_taxonomy_vocabulary_delete(\Drupal\taxonomy\Entity\Vocabulary $vocabulary) {
  module_load_include('inc', 'pp_taxonomy_manager', 'includes/pp_taxonomy_manager.admin');
  $configs = PPTaxonomyManagerConfig::loadMultiple();
  // Disconnect all PP Taxonomy manager configurations from this vocabulary.
  /** @var PPTaxonomyManagerConfig $config */
  foreach ($configs as $config) {
    $configuration = $config->getConfig();
    if (isset($configuration['taxonomies'][$vocabulary->id()])) {
      $manager = PPTaxonomyManager::getInstance($config);

      // Delete the connection.
      $manager->deleteConnection($vocabulary->id());

      // Delete all the logs and hash data.
      $manager->deleteSyncData($vocabulary->id());

      $connection = $config->getConnection();
      drupal_set_message(t('The connection between the Drupal taxonomy %taxonomy and the PoolParty server %server has been deleted successfully.', array(
        '%taxonomy' => $vocabulary->label(),
        '%server' => $connection->getTitle(),
      )));
    }
  }
}